### PR TITLE
erc selection view including show options button

### PR DESCRIPTION
**Pull request by TeKraft**
The show options button still has no function.
There is only a list of ERCs including a button that will later send information about the 2 ERCs to be substituted to the candidateView.

issue https://github.com/o2r-project/o2r-platform/issues/105

### CODE REVIEW

**Comment by nuest** [comment]
Can you add a screenshot?

**Comment by TeKraft** [comment]
at the moment the ERC list consists of all ERCs in the Database. Later on there should be given an array with ERC IDs (provided by the similarity analysis).

screenshot_ercselectionview

**Comment by MarkusKonk** [comment]
You might find an icon which is more suitable, something that indicates substitution. I think it also more meaningful if you change "show options" to "substitution options".

**Comment by MarkusKonk** [comment]
And the ERCs that are listed in the substitution tab should be clickable, ideally in a new tab I would say.

**Pull request merged**
